# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1kc35vwfh49cxymbxx3mm6ambsmp4bc26435ssr1cjyphp535y1r";
    aarch64-linux = "08x7qrh2qfbpsarg4fi9fq6qx4404n2d7wavksh0cnk6gs0wj1cy";
    x86_64-darwin = "110qv91nk66767hjgxkzyz68bcyfylspsb3yf5ik8cccjq5j6amk";
    aarch64-darwin = "05gaxcjb3qcmn9p2hqy2ymnk7kc1g8by9manryklx12nbnvdcdg6";
  };

  urlMap = {
    x86_64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "javascript-package-delegator";
  version = "1.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jpd $out/bin/jpd
  '';

  system = system;

  meta = {
    description = "A CLI for executing Javascript Package Manager Commands based on lock files. Supported's deno,bun, and all node package managers";
    homepage = "https://github.com/louiss0/javascript-package-delegator";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
