# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  shaMap = {
    x86_64-linux = "sha256-dqaKdIDqfZVq2kHwA3FrUlVkAX828itLQrUNZvbUJs4=";
    aarch64-linux = "sha256-FTgNYsutaTj82/XmauA56ww9TXQ6BiBZN6omYaPrLT8=";
    x86_64-darwin = "sha256-4y8oezSulNe7vjxJY/NBgGaO+ZPJehuMkGiEfivBhEM=";
    aarch64-darwin = "sha256-vjPjcQkA4IqQtUHa+DDta/yngeLOccAHZHDJZVL2WqY=";
  };

  urlMap = {
    x86_64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.0/javascript-package-delegator_1.0.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "javascript-package-delegator";
  version = "1.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jpd $out/bin/jpd
  '';

  system = system;

  meta = {
    description = "A CLI for executing Javascript Package Manager Commands based on lock files. Supported's deno,bun, and all node package managers";
    homepage = "https://github.com/louiss0/javascript-package-delegator";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
