# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1qinn26d0yvhrx7h7n91x55q9kgc2ifw7vj2w7q9bgs6hiq4qmww";
    aarch64-linux = "1bwkzbgn99iv2q2zy7cgpsfpr6sb740n6lkybxz0mjsc7j7hd4bn";
    x86_64-darwin = "048hd4lr0pzdzwzzqbb8y6bwnj4zq6bhdb29gnxxn50bh3vgn10q";
    aarch64-darwin = "1ki846hqs4c753ng8azqfxdg0gmmb2q95jwzfvyhlk545idxnrax";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Sheltons-CLI-Projects/javascript-package-delegator/releases/download/v3.0.1-alpha/javascript-package-delegator_3.0.1-alpha_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/Sheltons-CLI-Projects/javascript-package-delegator/releases/download/v3.0.1-alpha/javascript-package-delegator_3.0.1-alpha_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/Sheltons-CLI-Projects/javascript-package-delegator/releases/download/v3.0.1-alpha/javascript-package-delegator_3.0.1-alpha_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/Sheltons-CLI-Projects/javascript-package-delegator/releases/download/v3.0.1-alpha/javascript-package-delegator_3.0.1-alpha_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "javascript-package-delegator";
  version = "3.0.1-alpha";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jpd $out/bin/jpd
  '';

  meta = {
    description = "A CLI for executing JavaScript package manager commands based on lock files. Supports npm, yarn, pnpm, bun, and deno.";
    homepage = "https://github.com/Sheltons-CLI-Projects/javascript-package-delegator";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
